# Generated by Django 3.2.7 on 2021-10-24 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_string', models.TextField(max_length=1500)),
                ('database_string', models.TextField(max_length=1500)),
            ],
            options={
                'db_table': 'cir_database_context',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=768)),
                ('original_name', models.CharField(blank=True, max_length=768, verbose_name='Original Name')),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.context')),
            ],
            options={
                'db_table': 'cir_database',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_modified', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'cir_database_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='Group/Institute')),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.organization')),
            ],
            options={
                'db_table': 'cir_database_publisher',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecordURLScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.URLField()),
            ],
            options={
                'verbose_name': 'Record URL Scheme',
                'db_table': 'cir_database_record_url_scheme',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.URLField()),
            ],
            options={
                'verbose_name': 'URL',
                'db_table': 'cir_database_url',
                'ordering': ['string'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Original Name')),
                ('version', models.CharField(blank=True, max_length=255)),
                ('date_released', models.DateField(blank=True, verbose_name='Date Released')),
                ('classification', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], db_column='class', max_length=32)),
                ('status', models.CharField(blank=True, choices=[('active', 'Show'), ('inactive', 'Hide')], max_length=32)),
                ('file_name_pattern', models.CharField(blank=True, max_length=255, verbose_name='File Name Pattern')),
                ('cocoa_release_id', models.IntegerField(blank=True, verbose_name='COCOA ID')),
                ('csls_id', models.IntegerField(blank=True, verbose_name='CSLS ID')),
                ('pubchem_id', models.IntegerField(blank=True, verbose_name='PubChem Database ID')),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_modified', models.DateTimeField(blank=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.publisher')),
                ('record_url_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.recordurlscheme', verbose_name='Record URL Scheme')),
                ('url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.url', verbose_name='URL')),
            ],
            options={
                'db_table': 'cir_database_release',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.url', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.url', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='database',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.publisher'),
        ),
        migrations.AddField(
            model_name='database',
            name='record_url_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.recordurlscheme', verbose_name='Record URL Scheme'),
        ),
        migrations.AddField(
            model_name='database',
            name='url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.url', verbose_name='URL'),
        ),
    ]
