# Generated by Django 4.0 on 2022-02-03 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'verbose_name': 'Context Teg',
                'verbose_name_plural': 'Context Tags',
                'db_table': 'cir_database_context_tag',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=768)),
                ('href', models.URLField(blank=True, max_length=4096, null=True)),
                ('description', models.TextField(blank=True, max_length=4096, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_database',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('href', models.URLField(blank=True, max_length=4096, null=True)),
                ('classification', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal'), ('legacy', 'Legacy')], db_column='class', max_length=32)),
                ('status', models.CharField(blank=True, choices=[('active', 'Show'), ('inactive', 'Hide')], max_length=32)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('released', models.DateField(blank=True, null=True, verbose_name='Date Released')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_database_release',
                'ordering': ['-added'],
            },
        ),
        migrations.CreateModel(
            name='URIPattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=32768)),
                ('category', models.CharField(choices=[('schema', 'Schema'), ('uritemplate', 'URI Template (RFC6570)'), ('documentation', 'Documentation (HTML, PDF)')], default='uritemplate', max_length=16)),
                ('description', models.TextField(blank=True, max_length=32768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_database_uri_pattern',
                'ordering': ['-added'],
            },
        ),
        migrations.AddConstraint(
            model_name='uripattern',
            constraint=models.UniqueConstraint(fields=('uri', 'category'), name='unique_uripattern_constraint'),
        ),
        migrations.AddField(
            model_name='release',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database'),
        ),
        migrations.AddField(
            model_name='release',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolver.publisher'),
        ),
        migrations.AddField(
            model_name='release',
            name='record_uri_pattern',
            field=models.ManyToManyField(to='database.URIPattern'),
        ),
        migrations.AddField(
            model_name='database',
            name='context_tags',
            field=models.ManyToManyField(to='database.ContextTag'),
        ),
        migrations.AddField(
            model_name='database',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolver.publisher'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('database', 'publisher', 'version', 'released'), name='unique_database_release_constraint'),
        ),
        migrations.AddConstraint(
            model_name='database',
            constraint=models.UniqueConstraint(fields=('name', 'publisher'), name='unique_database_constraint'),
        ),
    ]
