# Generated by Django 4.0 on 2022-02-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='name',
            field=models.CharField(default=None, max_length=768),
            preserve_default=False,
        ),
    ]
