# Generated by Django 4.0 on 2022-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uripattern',
            name='name',
            field=models.CharField(default=None, max_length=768),
            preserve_default=False,
        ),
    ]
