# Generated by Django 4.0 on 2022-02-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_uripattern_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='release',
            name='unique_database_release_constraint',
        ),
        migrations.AddField(
            model_name='release',
            name='downloaded',
            field=models.DateField(blank=True, null=True, verbose_name='Date Downloaded'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('database', 'publisher', 'version', 'downloaded', 'released'), name='unique_database_release_constraint'),
        ),
    ]
