# Generated by Django 4.0 on 2022-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_release_unique_database_release_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='release',
            name='unique_database_release_constraint',
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('database', 'publisher', 'name', 'version', 'downloaded', 'released'), name='unique_database_release_constraint'),
        ),
    ]
