#!/bin/bash

cp app.env .env
source .env

#TODO; bad idea for hard-coded version here
docker tag cactvs-django-app-server:$APP_VERSION $APP_NAME:$APP_VERSION

if [ -z $(docker network ls --filter name=^${APP_NAME}-backend$ --format="{{ .Name }}") ] ; then
     echo "creating Docker network"
     docker network create cirx-backend ;
fi

./docker-build
#./django-init
#./django-manage-py initdata
#./django-manage-py loaddata structure


echo "done"


exit 0
