#!/bin/bash
set -e

./django-manage-py makemigrations &&\
./django-manage-py makemigrations resolver structure &&\
./django-manage-py migrate &&\
./django-manage-py collectstatic &&\
./django-manage-py createsuperuser



