#!/bin/bash
set -e

./django-manage-py makemigrations structure resolver database etl django_celery_results &&\
./django-manage-py migrate &&\
./django-manage-py collectstatic --noinput &&\
./django-manage-py createsuperuser --noinput



