#!/bin/bash
set -e

echo "Running $@"

#docker-compose exec app bash -ci "gosu app bash -c 'cd /home/app/appsite && ./manage.py $*'"
docker-compose run --rm app bash -ci "gosu app bash -c 'cd /home/app/appsite && ./manage.py $*'"
