version: '3.9'

services:

  cirx:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
    ports:
      - ${APP_CONNECTION_PORT}:80
    networks:
      - app_network
    environment:
      - APP_NAME
      - APP_VERSION
      - APP_UID
      - APP_GID
      - APP_VIRTUAL_HOSTNAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
    depends_on:
      - cirx-postgres
    entrypoint: [ "/home/app/docker-entrypoint.sh" ]
    command: [ "/home/nginx/run.sh" ]


  cirx-postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql
    networks:
      - app_network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER

volumes:
  postgres_db_volume:
    name: ${APP_NAME}-postgres-db-volume

networks:
  app_network:
    external:
      name: ${APP_NAME}-backend


