version: '3.9'

services:

  cirx:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
    ports:
      - ${APP_CONNECTION_PORT}:80
    networks:
      - app_network
    environment:
      - APP_NAME
      - APP_VERSION
      - APP_UID
      - APP_GID
      - APP_VIRTUAL_HOSTNAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - DJANGO_SUPERUSER_USERNAME
      - DJANGO_SUPERUSER_PASSWORD
      - DJANGO_SUPERUSER_EMAIL
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
      - LETSENCRYPT_TEST
    depends_on:
      - cirx-postgres
    entrypoint: [ "/home/app/docker-entrypoint.sh" ]
    command: [ "/home/nginx/run.sh" ]

  cirx-postgres:
    image: postgres:latest
    container_name: ${APP_NAME}-postgres
    volumes:
      - postgres_db_volume:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - app_network
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER


  cirx-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: ${APP_NAME}-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/
      - rabbitmq_volume:/var/log/rabbitmq
    networks:
      - app_network
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 10

  cirx-worker:
    image: ${APP_NAME}:${APP_VERSION}
    container_name: ${APP_NAME}-python
    volumes:
      - ${APP_HOME}:/home/app
      - ${APP_HOME}/nginx:/home/nginx
      #    ports:
      #      - "8000:8000"
    networks:
      - app_network
    environment:
      - APP_NAME
      - APP_VERSION
      - APP_UID
      - APP_GID
      - APP_VIRTUAL_HOSTNAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_PORT
      - POSTGRES_PASSWORD
      - VIRTUAL_HOST=${APP_VIRTUAL_HOSTNAME}
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - PYTHONSTARTUP=/home/app/cactvsenv/__init__.py
    entrypoint: [ "/home/app/docker-entrypoint.worker.sh" ]
    working_dir: "/home/app"
    command: python
    restart: on-failure
    depends_on:
      - cirx-rabbitmq

volumes:
  postgres_db_volume:
    name: ${APP_NAME}-postgres-db-volume
  rabbitmq_volume:
    name: ${APP_NAME}-rabbitmq_volume

networks:
  app_network:
    external:
      name: ${APP_NAME}-backend


