#!/bin/bash

cp app.env .env
source .env

docker tag cactvs-django-app-server:1.0 $APP_NAME:$APP_VERSION

if [ -z $(docker network ls --filter name=^${APP_NAME}-backend$ --format="{{ .Name }}") ] ; then
     echo "creating Docker network"
     docker network create cirx-backend ;
fi

./build
./django-init
./django-manage-py initdata


echo "done"


exit 0
