#!/bin/bash
set -e

source .env

#date=$(date +"%Y-%m-%d")

for table in "cir_structure" "cir_structure_parent_structure"
do
  destination=backup/partial/${table}.copy.gz
  docker-compose exec cirx-postgres /bin/bash -c "PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME -c \"\copy ${table} to STDOUT\"" | gzip -9  > ${destination}
  echo 'wrote backup to destination:' ${destination}
done

