#!/bin/bash
set -e

source .env

date=$(date +"%Y-%m-%d")

destination=backup/partial/cir_structure.copy.gz.${date}

docker-compose exec cirx-postgres /bin/bash -c "
    gunzip -c /home/app/backup/partial/restore/cir_structure.copy.gz.2024-03-10 |
    PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME -c \"\copy cir_structure from STDIN\""

#docker-compose exec cirx-postgres psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME "$@"


echo 'done'