#!/bin/bash
set -e

source .env

date=$(date +"%Y-%m-%d")

destination=backup/partial/cir_structure.copy.gz.${date}

docker-compose exec cirx-postgres /bin/bash -c "
    PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME
    -c \"\copy cir_structure to STDOUT\"" | gzip -9  > ${destination}



echo 'wrote backup to destination:' ${destination}