#!/bin/bash
set -e

source .env

SUID=$(id -u)
SGUID=$(id -g)

DESTINATION=/home/app/backup/full
CHOWNER="${SUID}:${SGUID}"

docker-compose exec cirx-postgres /bin/bash -c "\
  PGPASSWORD=$POSTGRES_PASSWORD\
  pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME\
  -Fd $POSTGRES_NAME -j 8 -f ${DESTINATION};\
  chown ${CHOWNER} -R ${DESTINATION}\
"



