#!/bin/bash
set -e

source .env

docker-compose exec cirx-postgres /bin/bash -c "PGPASSWORD=Arg0 pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME -a -t cir_structure -t cir_structure_parent_structure" | gzip -9  > cir_structure.sql.gz

#docker-compose exec cirx-postgres /bin/bash -c "PGPASSWORD=Arg0 pg_dump -h $POSTGRES_HOST -U $POSTGRES_USER $POSTGRES_NAME -Ft -a -t cir_structure -t cir_structure_parent_structure" > cir_structure.tar



