#!/bin/bash
set -e

source .env

#docker-compose exec cirx-postgres /bin/bash -c "
#  gunzip -c /home/app/backup/full/cir_database.sql.gz | psql -d postgres -U postgres
#"

SOURCE=/home/app/backup/dump

echo $SOURCE
echo $POSTGRES_NAME

docker-compose exec cirx-postgres /bin/bash -c "\
  PGPASSWORD=$POSTGRES_PASSWORD\
  pg_restore --clean -j 8 -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_USER $SOURCE\
"


echo "done"