#!/bin/bash
set -e

source .env

#docker-compose exec cirx-postgres /bin/bash -c "
#  gunzip -c /home/app/backup/full/cir_database.sql.gz | psql -d postgres -U postgres
#"

source=/home/app/backup/dump

echo $source
echo $POSTGRES_NAME

docker-compose exec cirx-postgres /bin/bash -c "PGPASSWORD=$POSTGRES_PASSWORD pg_restore --clean  -j 5 -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_USER /home/app/backup/dump"

#pg_restore -d postgres --clean --create db.dump

echo "done"