# Generated by Django 3.2.7 on 2021-12-02 16:05

import custom.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, db_column='dateTime')),
            ],
            options={
                'db_table': 'cir_access',
            },
        ),
        migrations.CreateModel(
            name='AccessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'cir_access_client',
            },
        ),
        migrations.CreateModel(
            name='AccessHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=255, unique=True)),
                ('blocked', models.IntegerField()),
                ('lock_timestamp', models.DateTimeField(db_column='lock_time')),
                ('current_sleep_period', models.IntegerField()),
                ('force_sleep_period', models.IntegerField()),
                ('force_block', models.IntegerField()),
            ],
            options={
                'db_table': 'cir_access_host',
            },
        ),
        migrations.CreateModel(
            name='AccessHostOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cir_access_host_organization',
            },
        ),
        migrations.CreateModel(
            name='AccessOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'cir_access_organization',
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cir_record_compound_associations',
            },
        ),
        migrations.CreateModel(
            name='AssociationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=48)),
                ('property', models.CharField(max_length=48)),
                ('display_name', models.CharField(max_length=48)),
            ],
            options={
                'db_table': 'cir_record_compound_association_type',
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cir_compound',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cir_structure_formula',
            },
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1500, unique=True)),
            ],
            options={
                'db_table': 'cir_structure_name',
            },
        ),
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'cir_name_type',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficts_compound', models.IntegerField(db_column='ficts_compound_id')),
                ('ficus_compound', models.IntegerField(db_column='ficus_compound_id')),
                ('uuuuu_compound', models.IntegerField(db_column='uuuuu_compound_id')),
                ('database_record_external_identifier', models.CharField(max_length=100)),
                ('release_record_external_identifier', models.CharField(max_length=100)),
                ('revision', models.IntegerField(db_column='revision_id')),
            ],
            options={
                'db_table': 'cir_record_lookup',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromString', models.TextField()),
                ('response', models.TextField(db_column='string')),
                ('responseFile', models.FileField(max_length=255, upload_to='tmp')),
            ],
            options={
                'db_table': 'cir_response',
            },
        ),
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('method', models.CharField(blank=True, max_length=255, null=True)),
                ('parameter', models.CharField(blank=True, max_length=1024, null=True)),
                ('base_mime_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'cir_response_type',
            },
        ),
        migrations.CreateModel(
            name='StandardInChI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(db_column='version_id')),
                ('key_layer1', models.CharField(db_column='key_layer1', max_length=14)),
                ('key_layer2', models.CharField(db_column='key_layer2', max_length=10)),
                ('key_layer3', models.CharField(db_column='key_layer3', max_length=1)),
                ('string', models.CharField(max_length=1500)),
            ],
            options={
                'db_table': 'cir_structure_standard_inchi',
            },
        ),
        migrations.CreateModel(
            name='Structure2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashisy', custom.fields.CactvsHashField(unique=True)),
                ('minimol', custom.fields.CactvsMinimolField()),
            ],
            options={
                'db_table': 'cir_structure_2',
            },
        ),
        migrations.CreateModel(
            name='StructureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashisy', models.IntegerField(unique=True)),
                ('small', models.TextField(max_length=65535)),
                ('medium', models.TextField(max_length=65535)),
                ('large', models.TextField(max_length=65535)),
            ],
            options={
                'db_table': 'cir_structure_image',
            },
        ),
        migrations.CreateModel(
            name='UsageMonth',
            fields=[
                ('month_year', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('requests', models.IntegerField()),
                ('ip_counts', models.IntegerField()),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'cir_usage_month',
            },
        ),
        migrations.CreateModel(
            name='UsageMonthDay',
            fields=[
                ('month_day', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('requests', models.IntegerField()),
                ('ip_counts', models.IntegerField()),
            ],
            options={
                'db_table': 'cir_usage_month_day',
            },
        ),
        migrations.CreateModel(
            name='UsageSeconds',
            fields=[
                ('requests', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cir_usage_seconds',
            },
        ),
        migrations.CreateModel(
            name='StructureStandardInChI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_inchi', models.ForeignKey(db_column='standard_inchi_id', on_delete=django.db.models.deletion.CASCADE, to='structure.standardinchi')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure2')),
            ],
            options={
                'db_table': 'cir_structure_standard_inchis',
            },
        ),
        migrations.CreateModel(
            name='StructureName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.name')),
                ('name_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.nametype')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure2')),
            ],
            options={
                'db_table': 'cir_structure_names',
            },
        ),
        migrations.AddField(
            model_name='structure2',
            name='names',
            field=models.ManyToManyField(related_name='structure', through='structure.StructureName', to='structure.Name'),
        ),
        migrations.AddField(
            model_name='structure2',
            name='standard_inchis',
            field=models.ManyToManyField(related_name='structure_set', through='structure.StructureStandardInChI', to='structure.StandardInChI'),
        ),
        migrations.AddConstraint(
            model_name='standardinchi',
            constraint=models.UniqueConstraint(fields=('version', 'key_layer1', 'key_layer2', 'key_layer3'), name='unique_standard_inchi_key'),
        ),
        migrations.AddField(
            model_name='responsetype',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.responsetype'),
        ),
        migrations.AddField(
            model_name='response',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.responsetype'),
        ),
        migrations.AddField(
            model_name='record',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database'),
        ),
        migrations.AddField(
            model_name='record',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.release'),
        ),
        migrations.AddField(
            model_name='compound',
            name='structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compound', to='structure.structure2'),
        ),
        migrations.AddField(
            model_name='association',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_associations', to='structure.compound'),
        ),
        migrations.AddField(
            model_name='association',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compound_associations', to='structure.record'),
        ),
        migrations.AddField(
            model_name='association',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.associationtype'),
        ),
        migrations.AddField(
            model_name='accesshostorganization',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.accesshost'),
        ),
        migrations.AddField(
            model_name='accesshostorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.accessorganization'),
        ),
        migrations.AddField(
            model_name='accesshost',
            name='organization',
            field=models.ManyToManyField(through='structure.AccessHostOrganization', to='structure.AccessOrganization'),
        ),
        migrations.AddField(
            model_name='access',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.accessclient'),
        ),
        migrations.AddField(
            model_name='access',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.accesshost'),
        ),
        migrations.AddConstraint(
            model_name='structurename',
            constraint=models.UniqueConstraint(fields=('name', 'structure', 'name_type'), name='unique_structure_names'),
        ),
        migrations.AlterUniqueTogether(
            name='accesshostorganization',
            unique_together={('host', 'organization')},
        ),
    ]
