# Generated by Django 4.1.10 on 2023-08-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsetype',
            name='url',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
