# Generated by Django 3.2.7 on 2021-12-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InChI',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('version_string', models.CharField(max_length=64)),
                ('block1', models.CharField(max_length=14)),
                ('block2', models.CharField(max_length=10)),
                ('block3', models.CharField(max_length=1)),
                ('key', models.CharField(blank=True, max_length=27, null=True)),
                ('string', models.CharField(blank=True, max_length=32768, null=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('safe_options', models.CharField(default=None, max_length=2, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'InChI',
            },
        ),
        migrations.AddConstraint(
            model_name='inchi',
            constraint=models.UniqueConstraint(fields=('version', 'block1', 'block2', 'block3'), name='unique_inchi_constraint'),
        ),
    ]
