# Generated by Django 3.2.7 on 2021-12-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20211202_2326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inchi',
            table='cir_inchi',
        ),
    ]
