# Generated by Django 3.2.7 on 2021-10-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20211014_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='hashisy',
            field=models.BigIntegerField(unique=True),
        ),
    ]
