# Generated by Django 3.2.7 on 2021-12-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_inchi_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureInChIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.inchi')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structure2')),
            ],
            options={
                'db_table': 'cir_structure_inchis',
            },
        ),
    ]
