# Generated by Django 3.2.7 on 2021-10-22 09:50

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_alter_structure_hashisy'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureCactvsHash',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hashisy', custom.fields.CactvsHashField(unique=True)),
                ('name', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'cir_structure_hash',
            },
        ),
    ]
