# Generated by Django 3.2.7 on 2021-10-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_structurecactvshash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurecactvshash',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
