# Generated by Django 3.2.7 on 2021-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_structurecactvshash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurecactvshash',
            name='minimol',
            field=models.BinaryField(null=True),
        ),
    ]
