# Generated by Django 3.2.7 on 2021-10-24 16:23

import custom.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_structurecactvshash_minimol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashisy', custom.fields.CactvsHashField(unique=True)),
                ('minimol', custom.fields.CactvsMinimolField()),
            ],
        ),
    ]
