# Generated by Django 3.2.7 on 2021-10-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_structure2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='structure2',
            table='cir_structure_2',
        ),
    ]
