# Generated by Django 4.0.4 on 2022-09-27 17:21

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNameField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_regid', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cir_release_name_field',
            },
        ),
        migrations.CreateModel(
            name='StructureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, storage=django.core.files.storage.FileSystemStorage(location='/filestore'), upload_to='manual/')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cir_structure_file',
            },
        ),
        migrations.CreateModel(
            name='StructureFileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location_pattern_string', models.CharField(default='*', max_length=2048)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_structure_file_collection',
            },
        ),
        migrations.CreateModel(
            name='StructureFileCollectionPreprocessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='generic', max_length=2048)),
                ('params', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'cir_structure_file_collection_preprocessor',
            },
        ),
        migrations.CreateModel(
            name='StructureFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=768, unique=True)),
            ],
            options={
                'db_table': 'cir_structure_file_field',
            },
        ),
        migrations.CreateModel(
            name='StructureFileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cir_structure_file_record',
            },
        ),
        migrations.CreateModel(
            name='StructureFileRecordRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cir_structure_file_record_releases',
            },
        ),
    ]
