# Generated by Django 4.0.2 on 2022-04-16 20:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location_pattern_string', models.CharField(blank=True, max_length=2048, null=True)),
                ('description', models.TextField(blank=True, max_length=768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_structure_file_collection',
            },
        ),
        migrations.CreateModel(
            name='StructureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=1024, storage=django.core.files.storage.FileSystemStorage(location='/home/app/filestore'), upload_to='manual/')),
                ('count', models.IntegerField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cir_structure_file',
            },
        ),
        migrations.CreateModel(
            name='StructureFileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=768, unique=True)),
            ],
            options={
                'db_table': 'cir_structure_file_field',
            },
        ),
        migrations.CreateModel(
            name='StructureFileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('processed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cir_structure_file_record',
            },
        ),
    ]
