# Generated by Django 4.0 on 2022-02-03 17:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_location_pattern_string', models.CharField(blank=True, max_length=2048, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='database.release')),
            ],
            options={
                'db_table': 'cir_structure_file_collection',
            },
        ),
        migrations.CreateModel(
            name='StructureFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(max_length=1024, storage=django.core.files.storage.FileSystemStorage(location='/home/app/filestore'), upload_to='manual/')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='etl.filecollection')),
            ],
            options={
                'db_table': 'cir_structure_file',
            },
        ),
        migrations.AddConstraint(
            model_name='structurefile',
            constraint=models.UniqueConstraint(fields=('collection', 'name'), name='unique_structure_file_constraint'),
        ),
    ]
