# Generated by Django 4.0.2 on 2022-04-10 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        ('etl', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurefilerecord',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure2'),
        ),
        migrations.AddField(
            model_name='structurefilerecord',
            name='structure_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.structurefile'),
        ),
        migrations.AddField(
            model_name='structurefilefield',
            name='structure_files',
            field=models.ManyToManyField(related_name='fields', to='etl.StructureFile'),
        ),
        migrations.AddField(
            model_name='structurefile',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='etl.filecollection'),
        ),
        migrations.AddField(
            model_name='filecollection',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='database.release'),
        ),
        migrations.AddConstraint(
            model_name='structurefilerecord',
            constraint=models.UniqueConstraint(fields=('structure_file', 'number'), name='unique_structure_file__record_constraint'),
        ),
        migrations.AddConstraint(
            model_name='structurefile',
            constraint=models.UniqueConstraint(fields=('collection', 'file'), name='unique_structure_file_constraint'),
        ),
        migrations.AddConstraint(
            model_name='filecollection',
            constraint=models.UniqueConstraint(fields=('release', 'file_location_pattern_string'), name='unique_file_collection_constraint'),
        ),
    ]
