# Generated by Django 4.0.2 on 2022-03-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurefilerecord',
            name='hashisy',
        ),
        migrations.AddField(
            model_name='structurefilerecord',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.structure2'),
        ),
    ]
