# Generated by Django 4.0.4 on 2022-10-09 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureFileStatus',
            fields=[
                ('structure_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='etl.structurefile')),
                ('normalization', models.DateTimeField(auto_now_add=True)),
                ('normalization_finished', models.BooleanField(default=False)),
                ('inchi_calculation', models.DateTimeField(auto_now_add=True)),
                ('inchi_calculation_finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cir_structure_file_status',
            },
        ),
        migrations.RemoveField(
            model_name='structurefile',
            name='processed',
        ),
    ]
