# Generated by Django 4.0.4 on 2022-10-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_alter_structurehashisy_structure_and_more'),
        ('etl', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureFileSource',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='structure_file_source', serialize=False, to='resolver.structure')),
                ('structure_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_file_source', to='etl.structurefile')),
            ],
            options={
                'db_table': 'cir_structure_file_source',
            },
        ),
    ]
