# Generated by Django 4.0.4 on 2022-09-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structurefilerecordrelease',
            old_name='structure_file',
            new_name='structure_file_record',
        ),
    ]
