# Generated by Django 4.2.3 on 2023-11-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefiletag',
            name='process',
            field=models.CharField(choices=[('addfiles', 'Add Files'), ('register', 'Registation'), ('normalize', 'Normalization'), ('calcinchi', 'InChI Calculation'), ('linkname', 'Name Linking'), ('none', 'None')], default='none', max_length=16),
        ),
    ]
