# Generated by Django 4.0.4 on 2022-11-27 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_structurefilesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefilerecordnameassociation',
            name='structure_file_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_file_record_name_associations', to='etl.structurefilerecord'),
        ),
    ]
