# Generated by Django 4.0.4 on 2022-10-09 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_structurefilestatus_remove_structurefile_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefilestatus',
            name='structure_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='file_status', serialize=False, to='etl.structurefile'),
        ),
    ]
