# Generated by Django 4.0.4 on 2022-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0003_rename_structure_file_structurefilerecordrelease_structure_file_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='structurefilerecordrelease',
            name='unique_structure_file_record_release_constraint',
        ),
        migrations.AddConstraint(
            model_name='structurefilerecordrelease',
            constraint=models.UniqueConstraint(fields=('structure_file_record', 'release'), name='unique_structure_file_record_release_constraint'),
        ),
    ]
