# Generated by Django 4.0.4 on 2022-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_structurefilestatus_structure_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurefilestatus',
            name='inchi_calculation',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='structurefilestatus',
            name='normalization',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
