# Generated by Django 4.0.4 on 2022-09-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_remove_structurefilerecordrelease_unique_structure_file_record_release_constraint_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='structurefilerecordrelease',
            table='cir_structure_file_record_releases',
        ),
    ]
