# Generated by Django 4.0.4 on 2022-12-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0004_alter_structurefilerecordnameassociation_structure_file_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureFileLinkNameStatus',
            fields=[
                ('structure_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='linkname_status', serialize=False, to='etl.structurefile')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('progress', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'cir_structure_file_structure_link_name_status',
            },
        ),
    ]
