# Generated by Django 4.0.4 on 2022-10-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0005_alter_structurefilestatus_inchi_calculation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureFileInChIStatus',
            fields=[
                ('structure_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inchi_status', serialize=False, to='etl.structurefile')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cir_structure_file_inchi_status',
            },
        ),
        migrations.CreateModel(
            name='StructureFileNormalizationStatus',
            fields=[
                ('structure_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='normalization_status', serialize=False, to='etl.structurefile')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cir_structure_file_normalization_status',
            },
        ),
        migrations.DeleteModel(
            name='StructureFileStatus',
        ),
    ]
