# Generated by Django 4.0.4 on 2022-09-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_releasenamefield_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='releasenamefield',
            old_name='name_field',
            new_name='structure_file_field',
        ),
    ]
