# Generated by Django 4.0.4 on 2022-10-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0006_structurefileinchistatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurefileinchistatus',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='structurefilenormalizationstatus',
            name='finished',
        ),
        migrations.AddField(
            model_name='structurefileinchistatus',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='structurefilenormalizationstatus',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
