# Generated by Django 4.0.4 on 2022-09-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl', '0007_rename_name_field_releasenamefield_structure_file_field'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='releasenamefield',
            name='unique_release_name_field_constraint',
        ),
        migrations.AddConstraint(
            model_name='releasenamefield',
            constraint=models.UniqueConstraint(fields=('release', 'structure_file_field', 'name_type'), name='unique_release_name_field_constraint'),
        ),
    ]
