# Generated by Django 4.0.2 on 2022-03-06 18:25

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('self', 'Self'), ('site', 'Site'), ('api', 'API'), ('resolver', 'Resolver')], default='site', max_length=16)),
                ('href', models.URLField(max_length=4096)),
                ('entrypoint_href', models.URLField(blank=True, max_length=4096, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=32768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.entrypoint')),
            ],
            options={
                'db_table': 'cir_entrypoint',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('description', models.TextField(blank=True, max_length=32768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cir_media_type',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32768)),
                ('abbreviation', models.CharField(blank=True, max_length=32, null=True)),
                ('category', models.CharField(choices=[('regulatory', 'Regulatory'), ('government', 'Government'), ('academia', 'Academia'), ('company', 'Company'), ('vendor', 'Vendor'), ('research', 'Research'), ('publishing', 'Publishing'), ('provider', 'Provider'), ('public', 'Public'), ('society', 'Society'), ('charity', 'Charity'), ('other', 'Other'), ('none', 'None')], default='none', max_length=16)),
                ('href', models.URLField(blank=True, max_length=4096, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.organization')),
            ],
            options={
                'db_table': 'cir_organization',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('entity', 'Entity'), ('service', 'Service'), ('network', 'Network'), ('division', 'Division'), ('group', 'Group'), ('person', 'Person'), ('other', 'Other'), ('none', 'None')], default='none', max_length=16)),
                ('name', models.CharField(max_length=1024)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=8192, null=True)),
                ('href', models.URLField(blank=True, max_length=4096, null=True)),
                ('orcid', models.URLField(blank=True, max_length=4096, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organizations', models.ManyToManyField(blank=True, related_name='publishers', to='resolver.Organization')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.publisher')),
            ],
            options={
                'db_table': 'cir_publisher',
            },
        ),
        migrations.CreateModel(
            name='InChI',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('version_string', models.CharField(blank=True, max_length=64, null=True)),
                ('block1', models.CharField(max_length=14)),
                ('block2', models.CharField(max_length=10)),
                ('block3', models.CharField(max_length=1)),
                ('key', models.CharField(max_length=27)),
                ('string', models.CharField(blank=True, max_length=32768, null=True)),
                ('is_standard', models.BooleanField(default=False)),
                ('safe_options', models.CharField(default=None, max_length=2, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('entrypoints', models.ManyToManyField(blank=True, related_name='inchis', to='resolver.EntryPoint')),
            ],
            options={
                'verbose_name': 'InChI',
                'verbose_name_plural': 'InChIs',
                'db_table': 'cir_inchi',
            },
        ),
        migrations.AddField(
            model_name='entrypoint',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrypoints', to='resolver.publisher'),
        ),
        migrations.CreateModel(
            name='EndPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uri', models.CharField(max_length=32768)),
                ('category', models.CharField(choices=[('schema', 'Schema'), ('uritemplate', 'URI Template (RFC6570)'), ('documentation', 'Documentation (HTML, PDF)')], default='uritemplate', max_length=16)),
                ('request_methods', multiselectfield.db.fields.MultiSelectField(choices=[('GET', 'GET'), ('HEAD', 'HEAD'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('CONNECT', 'CONNECT'), ('OPTIONS', 'OPTIONS'), ('TRACE', 'TRACE'), ('PATCH', 'PATCH')], default=['GET'], max_length=52)),
                ('description', models.TextField(blank=True, max_length=32768, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('accept_header_media_types', models.ManyToManyField(related_name='accepting_endpoints', to='resolver.MediaType')),
                ('content_media_types', models.ManyToManyField(related_name='delivering_endpoints', to='resolver.MediaType')),
                ('entrypoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endpoints', to='resolver.entrypoint')),
                ('request_schema_endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_requesting_endpoints', to='resolver.endpoint')),
                ('response_schema_endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schema_responding_endpoints', to='resolver.endpoint')),
            ],
            options={
                'db_table': 'cir_endpoint',
            },
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(fields=('parent', 'name', 'category', 'href', 'orcid'), name='unique_publisher_constraint'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_organization_constraint'),
        ),
        migrations.AddConstraint(
            model_name='inchi',
            constraint=models.UniqueConstraint(fields=('version', 'block1', 'block2', 'block3'), name='unique_inchi_constraint'),
        ),
        migrations.AddConstraint(
            model_name='entrypoint',
            constraint=models.UniqueConstraint(fields=('parent', 'publisher', 'href'), name='unique_entrypoint_constraint'),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('entrypoint', 'uri'), name='unique_endpoint_constraint'),
        ),
    ]
