# Generated by Django 4.0.4 on 2022-07-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureinchiassociation',
            name='inchitype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='associations', to='resolver.inchitype'),
        ),
    ]
