# Generated by Django 4.2.3 on 2023-10-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureparentstructure',
            options={'verbose_name': 'Structure Parent', 'verbose_name_plural': 'Structure Parents'},
        ),
    ]
