# Generated by Django 4.0.4 on 2022-10-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='ficts_parent',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='ficus_parent',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='hashisy',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='uuuuu_parent',
        ),
        migrations.CreateModel(
            name='StructureParentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficts_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficts_children', to='resolver.structure')),
                ('ficus_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ficus_children', to='resolver.structure')),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resolver.structure')),
                ('uuuuu_parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uuuuu_children', to='resolver.structure')),
            ],
        ),
        migrations.CreateModel(
            name='StructureHashisy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashisy', models.CharField(db_index=True, max_length=16)),
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='resolver.structure')),
            ],
        ),
    ]
