# Generated by Django 4.0.4 on 2022-10-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='unique_record',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'release'), name='unique_record'),
        ),
    ]
