# Generated by Django 4.0 on 2022-02-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publisher',
            name='unique_publisher_constraint',
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(fields=('parent', 'name', 'category', 'href', 'orcid'), name='unique_publisher_constraint'),
        ),
    ]
