# Generated by Django 4.2.3 on 2023-12-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inchi',
            name='unique_inchi_constraint',
        ),
    ]
