# Generated by Django 4.0.4 on 2022-09-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='publisher',
            name='unique_publisher_constraint',
        ),
        migrations.AddConstraint(
            model_name='publisher',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_publisher_constraint'),
        ),
    ]
