# Generated by Django 4.0.4 on 2022-09-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_alter_nametype_public_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='nametype',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resolver.nametype'),
        ),
    ]
