# Generated by Django 4.0.4 on 2022-10-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_remove_structure_ficts_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structurehashisy',
            name='id',
        ),
        migrations.RemoveField(
            model_name='structureparentstructure',
            name='id',
        ),
        migrations.AlterField(
            model_name='structurehashisy',
            name='structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='resolver.structure'),
        ),
        migrations.AlterField(
            model_name='structureparentstructure',
            name='structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='resolver.structure'),
        ),
        migrations.AlterModelTable(
            name='structurehashisy',
            table='cir_structure_hashisy',
        ),
        migrations.AlterModelTable(
            name='structureparentstructure',
            table='cir_structure_parent',
        ),
    ]
