# Generated by Django 4.0.4 on 2022-09-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_remove_publisher_unique_publisher_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='endpoint',
            name='unique_endpoint_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='entrypoint',
            name='unique_entrypoint_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='organization',
            name='unique_organization_constraint',
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(default='0', max_length=255),
        ),
        migrations.AlterField(
            model_name='structureinchiassociation',
            name='save_opt',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('category', 'uri'), name='unique_endpoint_constraint'),
        ),
        migrations.AddConstraint(
            model_name='entrypoint',
            constraint=models.UniqueConstraint(fields=('category', 'href'), name='unique_entrypoint_constraint'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_organization_constraint'),
        ),
    ]
