# Generated by Django 4.2.8 on 2024-02-10 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_pubchemstructurenamecids_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PubchemStructureNameCIDs',
        ),
    ]
