# Generated by Django 4.0.4 on 2022-10-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_remove_record_unique_record_record_unique_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurehashisy',
            name='structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='hashisy', serialize=False, to='resolver.structure'),
        ),
        migrations.AlterField(
            model_name='structureparentstructure',
            name='structure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='parents', serialize=False, to='resolver.structure'),
        ),
    ]
