# Generated by Django 4.2.3 on 2023-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_loadname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadname',
            name='hash',
            field=models.UUIDField(db_index=True),
        ),
    ]
