# Generated by Django 4.0.4 on 2022-10-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_alter_structurehashisy_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameAffinityClass',
            fields=[
                ('id', models.CharField(editable=False, max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=32768, null=True)),
            ],
            options={
                'db_table': 'cir_name_affinity_class',
            },
        ),
        migrations.RemoveConstraint(
            model_name='structurenameassociation',
            name='unique_structure_names',
        ),
        migrations.AddField(
            model_name='structurenameassociation',
            name='affinity_class',
            field=models.CharField(choices=[('exact', 'Exact'), ('narrow', 'Narrow'), ('broad', 'Broad'), ('unknown', 'Unknown'), ('unspecified', 'Unspecified'), ('generic', 'Generic'), ('related', 'Related')], default='unspecified', max_length=16),
        ),
        migrations.AddField(
            model_name='structurenameassociation',
            name='confidence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
