# Generated by Django 4.0.4 on 2022-10-07 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0003_remove_structurehashisy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureparentstructure',
            name='ficts_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficts_children', to='resolver.structure'),
        ),
        migrations.AlterField(
            model_name='structureparentstructure',
            name='ficus_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ficus_children', to='resolver.structure'),
        ),
        migrations.AlterField(
            model_name='structureparentstructure',
            name='uuuuu_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uuuuu_children', to='resolver.structure'),
        ),
    ]
