# Generated by Django 4.0.4 on 2022-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0004_alter_structureparentstructure_ficts_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureinchiassociation',
            name='save_opt',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
