# Generated by Django 4.0.4 on 2022-10-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0004_nameaffinityclass_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='structurenameassociation',
            constraint=models.UniqueConstraint(fields=('name', 'structure', 'name_type'), name='unique_structure_names'),
        ),
        migrations.AddConstraint(
            model_name='structurenameassociation',
            constraint=models.UniqueConstraint(fields=('name', 'structure', 'affinity_class'), name='unique_structure_name_affinity'),
        ),
    ]
