# Generated by Django 4.0.4 on 2022-10-31 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0006_structurenameassociation_structure_name_association_confidence_limits'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='structurenameassociation',
            table='cir_structure_name_associations',
        ),
    ]
