# Generated by Django 4.0.4 on 2022-12-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0009_remove_structurenameassociation_unique_structure_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structure',
            name='names',
        ),
        migrations.AlterField(
            model_name='structurenameassociation',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='resolver.structure'),
        ),
    ]
