# Generated by Django 4.0.4 on 2023-01-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0010_remove_structure_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structurenameassociation',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='resolver.name'),
        ),
    ]
